import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Splide, SplideSlide } from '@splidejs/react-splide'
import '@splidejs/react-splide/css'
import { themeChange } from 'theme-change'
import React from 'react'
import { setPage, useStateValue } from '../lib/state'
import StyferLogo from '../components/StyferLogo'

const Welcome: NextPage = () => {
  const [, dispatch] = useStateValue()
  React.useEffect(() => {
    themeChange(false)
  })

  const splideOptions = {
    padding: 0,
    type: 'loop',
    autoplay: true,
    interval: 3000,
  }

  return (
    <div className="sm:container min-h-screen mx-auto">
      <Head>
        <title>Styfer</title>
        <meta
          name="description"
          content="Styfer, Style Transfer, is a web-app that transfer artist (painter) style to your image using an artificial intelligence"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-evenly gap-8 w-full h-full px-4 py-12">
        <div className="text-center">
          <StyferLogo />
          <h1 className="text-4xl font-bold leading-none">
            STY
            <span className="text-primary">FER</span>
          </h1>
          <h2 className="text-xs leading-none font-light tracking-[0.2em]">
            by braincore
          </h2>
        </div>

        <div className="text-center">
          <p className="text-5xl font-bold">Transfer</p>
          <p className="text-5xl font-bold text-primary">Your Style</p>
          <p className="text-xs font-light mt-2">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore.
          </p>
        </div>

        <Splide
          options={splideOptions}
          aria-label="example image generated by Styfer"
        >
          <SplideSlide>
            <div className="w-full aspect-square shrink-0 bg-primary border border-2 border-base-content rounded-lg shadow-md" />
          </SplideSlide>
          <SplideSlide>
            <div className="w-full aspect-square shrink-0 bg-secondary border border-2 border-base-content rounded-lg shadow-md" />
          </SplideSlide>
          <SplideSlide>
            <div className="w-full aspect-square shrink-0 bg-accent border border-2 border-base-content rounded-lg shadow-md" />
          </SplideSlide>
          <div className="splide__arrows hidden" />
        </Splide>

        <div className="mx-auto flex flex-col md:flex-row gap-2 justify-center">
          <Link href="/create">
            <a
              onClick={() => dispatch(setPage('create'))}
              className="w-64 btn btn-lg btn-primary rounded-full"
            >
              Get Started
            </a>
          </Link>
          <Link href="/home">
            <a
              onClick={() => dispatch(setPage('home'))}
              className="w-64 btn btn-lg btn-primary rounded-full btn-outline"
            >
              View Gallery
            </a>
          </Link>
        </div>
      </div>
    </div>
  )
}

export default Welcome
